### ISSUE TITLE
API integration

### ISSUE THREAD

**Issue by Appelpitje** [mohabhassan/dgamexwrapper#3]
Is it possible to integrate an API?

**Comment by mohabhassan** [comment]
What kind of api ? a plugin api or some sorta network api?
both are possible :)

**Comment by doublekill98** [comment]
if you do that i will able to make elgbot to send the stats to a website.
That would be awesome.

**Comment by Appelpitje** [comment]
indeed a network api would be awesome to have

**Comment by mohabhassan** [comment]
That will be in there next release, as well as the remaining reborn client/rcon commands and spearhead support.

**Comment by mohabhassan** [comment]
Implemented with release v1.1.0!
